### ISSUE TITLE
Emails showing white background (unlike official dark mode)

### ISSUE THREAD

**Issue by g0rdonL** [dracula/mailspring#13]
Here is an example:
Dracula:
![image](https://user-images.githubusercontent.com/22794866/168491878-537ff16d-4201-4e7e-b61b-4c626a7a32c3.png)
vs Original Dark Theme from Mailspring:
![image](https://user-images.githubusercontent.com/22794866/168491904-0bbf1320-ea60-4e5e-9494-9567b63fdd05.png)

**Comment by avelino** [comment]
related #6
