### ISSUE TITLE
Text readability MailSpring issue

### ISSUE THREAD

**Issue by diorcula** [dracula/mailspring#6]
I found that some mails have dark text and that because of this the readability is very low.

![image](https://user-images.githubusercontent.com/32682696/104850721-13f33280-58f1-11eb-898f-dc7147e34f67.png)

Where the normal dark theme makes the text stand out more in the reading panel:
![image](https://user-images.githubusercontent.com/32682696/104850781-5ddc1880-58f1-11eb-87a8-f9bede60c80b.png)

**Comment by sarrietav-dev** [comment]
Even when there's a white background
![image](https://user-images.githubusercontent.com/25210925/105927542-346a6d80-6012-11eb-94a4-be0fa03831e5.png)

**Comment by avelino** [comment]
has been declared the control variable dark and light, but the mailspring is not working as it should, needs to debug to identify the problem

**Comment by avelino** [comment]
@bengotow help this issue pls

**Comment by sarrietav-dev** [comment]
I've tried other dark themes and they kind of have the same issue. But it would be good to figure out how to solve it.

**Comment by g0rdonL** [comment]
This doesnt happen when using the dark theme that comes with Mailspring

**Comment by avelino** [comment]
@CodeMouse92 help this issue pls
https://community.getmailspring.com/t/custom-theme-dark-does-not-inject-css-into-the-email-body-iframe/1547

**Comment by CodeMouse92** [comment]
@avelino I'm only the community manager; I don't know anything about themes. There are others on the Discourse who are more qualified to help than I am.

Also, tagging people in multiple places does not increase your chances of a response; it only clogs up notifications unnecessarily, and frustrates people. I'd have seen it on Discourse later today. :(

**Comment by lemonnuggets** [comment]
I found that the easiest way to deal with this was to use the default Mailspring UI Dark theme with Dracula colors, which is why I made [Mailspring UI Dark Dracula](https://github.com/lemonnuggets/mailspring-ui-dark-dracula).

I didn't really have time to dig in and figure out everything that the default UI Dark theme does differently so as to render decent dark theme emails but I hope this helps.

**Comment by avelino** [comment]
@lemonnuggets do you want to send pull request of your implementation for the official dracula theme?

I look forward to your contribution
