### ISSUE TITLE
Listing on Mailspring Community?

### ISSUE THREAD

**Issue by CodeMouse92** [dracula/mailspring#7]
Mailspring just launched an official Discourse community which will house the catalog for themes and plugins, among other things. It would be great to have this theme listed there: https://community.getmailspring.com/c/themes/9

@avelino if you join, we can also add you to the Theme Designers group.

**Comment by avelino** [comment]
@CodeMouse92 I tried to create a forum topic with the theme information, but I couldn't because I am a new member and can't send two links 

```markdown
## Description

[Dracula theme](https://draculatheme.com/mailspring), list on Dracula [site](https://draculatheme.com/mailspring).

## Screenshots

![Screenshot](https://draculatheme.com/static/img/screenshots/mailspring.png)

## Install

1. Download ZIP file, click [here](https://github.com/dracula/mailspring/archive/master.zip).
2. Open Mailspring, go to `Edit > Install Theme` and select the downloaded theme folder.
3. Change the current theme via `Edit > Change Theme`
```

![Screen Shot 2021-04-26 at 19 03 57](https://user-images.githubusercontent.com/31996/116156705-34861200-a6c2-11eb-936f-13f2ce377880.png)

**Comment by avelino** [comment]
> Hey there. We see you’ve been busy reading, which is fantastic, so we’ve promoted you up a trust level!

created https://community.getmailspring.com/t/dracula-theme-for-mailspring/1543
